[2022-09-17 18:20:47,015: INFO: 01_base_model_creation]: 
********************
[2022-09-17 18:20:47,015: INFO: 01_base_model_creation]: >>>>> stage creating base model started <<<<<
[2022-09-17 18:20:47,015: ERROR: 01_base_model_creation]: 'Namespace' object has no attribute 'params'
Traceback (most recent call last):
  File "src/01_base_model_creation.py", line 36, in <module>
    main(config_path=parsed_args.config, params_path=parsed_args.params)
AttributeError: 'Namespace' object has no attribute 'params'
[2022-09-17 18:21:11,592: INFO: 01_base_model_creation]: 
********************
[2022-09-17 18:21:11,593: INFO: 01_base_model_creation]: >>>>> stage creating base model started <<<<<
[2022-09-17 18:21:11,593: ERROR: 01_base_model_creation]: main() missing 1 required positional argument: 'params_path'
Traceback (most recent call last):
  File "src/01_base_model_creation.py", line 36, in <module>
    main(config_path=parsed_args.config)
TypeError: main() missing 1 required positional argument: 'params_path'
[2022-09-17 18:21:38,650: INFO: 01_base_model_creation]: 
********************
[2022-09-17 18:21:38,650: INFO: 01_base_model_creation]: >>>>> stage creating base model started <<<<<
[2022-09-17 18:21:38,650: ERROR: 01_base_model_creation]: main() missing 1 required positional argument: 'params_path'
Traceback (most recent call last):
  File "src/01_base_model_creation.py", line 36, in <module>
    main(config_path=parsed_args.config)
TypeError: main() missing 1 required positional argument: 'params_path'
[2022-09-17 18:23:16,905: INFO: 01_base_model_creation]: 
********************
[2022-09-17 18:23:16,905: INFO: 01_base_model_creation]: >>>>> stage creating base model started <<<<<
[2022-09-17 18:23:16,906: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-17 18:23:17,468: ERROR: 01_base_model_creation]: 'Sequential' object has no attribute 'sumary'
Traceback (most recent call last):
  File "src/01_base_model_creation.py", line 77, in <module>
    main(config_path=parsed_args.config)
  File "src/01_base_model_creation.py", line 64, in main
    model.sumary()
AttributeError: 'Sequential' object has no attribute 'sumary'
[2022-09-17 18:23:31,322: INFO: 01_base_model_creation]: 
********************
[2022-09-17 18:23:31,322: INFO: 01_base_model_creation]: >>>>> stage creating base model started <<<<<
[2022-09-17 18:23:31,323: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-17 18:23:31,797: INFO: 01_base_model_creation]: >>>>> stage creating base model completed!<<<<<

